config/routes.rb
LBCNew::Application.routes.draw do

  root 'page#index'

  get "cats/new"
  get "cats/show"
  get "cats/index"
  get "cats/edit"
  get "page/index"
  get "page/search"
  get "page/profil_search"
  get "page/new_admin"
  get "page/validation"
  get "profil/list"
  get "posts/new"
  get "posts/index"
  get "posts/show"
  get "posts/edit"
  get "reports/new"
  get "reports/show"
  get "reports/index"

  resources :cats
  resources :reports
  resources :posts do
    resources :comments
  end
  resources :profil
  devise_for :users

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :cat

  has_many :comments, dependent: :destroy

  has_attached_file :image1, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image1, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image2, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image2, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image3, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image3, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image4, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image4, :content_type => /\Aimage\/.*\Z/

  has_attached_file :image5, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image5, :content_type => /\Aimage\/.*\Z/

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :square => "100x100#"}, :default_url => "/images/avt/default-medium.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  def create
    @user = User.create( user_params )
    if @user.save
        AdminMailer.new_registration(@user).deliver
    end
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar)
  end

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_in){ |u| u.permit(:email, :password) }
     devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(:nom, :prenom, :promo, :email, :tel, :avatar, :password, :password_confirmation)}
     devise_parameter_sanitizer.for(:account_update){ |u| u.permit(:nom, :prenom, :promo, :email, :tel, :avatar, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def new
  end

  def show
    @cat = Cat.find(params[:id])
    @posts = Post.all
  end

  def index
    @cats = Cat.all
  end

  def edit
    @cat = Cat.find(params[:id])
  end


  def create
    @cat = Cat.new(cat_params)

    @cat.save
    redirect_to @cat
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to @cat
    else
      render 'edit'
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    redirect_to cats_path
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :icon)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(:user_id => current_user.id))
    redirect_to post_path(@post)

    # @comment = Comment.new(comment_params)
    #
    # @comment.save
    # redirect_to @comment
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)

    # @comment = Comment.find(params[:id])
    # @comment.destroy
    #
    # redirect_to comments_path
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :text)
    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def search
    @posts = Post.all
    @recherche = params[:q]
  end

  def profil_search
    @users = User.all
    @recherche = params[:q]
  end

  def new_admin
    @users = User.all
    @param_admin = params[:a]
  end

  def validation
    @users = User.all
    @param_val = params[:a]
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @author = current_user.id
    @cats = Cat.all
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(@post.user_id)
  end

  def edit
    @post = Post.find(params[:id])
    @cats = Cat.all
  end

  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)

    @post.save
    redirect_to @post
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :cat_id, :title, :price, :text, :image1, :image2, :image3, :image4, :image5)
    end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = Post.all
  end
  def list
    @users = User.all
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :authenticate_user!


  def new
  end

  def show
    @report = Report.find(params[:id])
  end

  def index
    @reports = Report.all
    @users = User.all
  end


  def create
    @report = Report.new(report_params)

    @report.save
    if @report.save
        AdminMailer.new_report(@report).deliver
    end
    redirect_to @report
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    redirect_to reports_path
  end

  private
    def report_params
      params.require(:report).permit(:text, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/cats/edit.html.haml
- if current_user.try(:admin?)

  = form_for :cat, url: cat_path(@cat), method: :patch do |f|
    - if @cat.errors.any?
      #error_explanation
        %h2
          = pluralize(@cat.errors.count, "error")
          prohibited
          this post from being saved:
        %ul
          - @cat.errors.full_messages.each do |msg|
            %li= msg
    %p
      = f.label :Nom
      %br/
      = f.text_field :name
    %p
      = f.label :Icon
      %br/
      = f.text_field :icon, placeholder: "Ex: 'glyphicon glyphicon-tag'"
    %p
      = f.submit

  = render 'icons'

- else

  Vous n'avez pas les permissions requises.

app/views/cats/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Catégories



- @cats.each do |c|
  %a.col-md-4{href: "/cats/#{c.id}"}
    .panel.panel-default.panel-body.cat-class
      .col-md-1
        %h2{class: "#{c.icon}"}
      .col-md-2.col-md-offset-1
        %h2
          = c.name
      .col-md-1.pull-right
        %h2
          = c.posts.count

.row
  .col-md-12
    .cat-idx-ftr
      %a{href: "/posts/new"}
        %button.btn.btn-primary{type: "button"}
          .glyphicon.glyphicon-edit
          Nouvelle annonce






%script $('#l2').attr('class','active')

:css
  .cat-class:hover {
    color: #e8d069;
    background-color: #15b5c1;
  }
  .cat-idx-ftr {
    padding-top: 9px;
    margin: 20px 0px 40px 0px;
    border-top: 1px solid #0d747c;
  }

app/views/cats/new.html.haml
- if current_user.try(:admin?)

  = form_for :cat, url: cats_path do |f|
    %p
      = f.label :Nom
      %br/
      = f.text_field :name
    %p
      = f.label :Icon
      %br/
      = f.text_field :icon, value: "glyphicon glyphicon-tag"
    %p
      = f.submit

  = render 'icons'

- else

  Vous n'avez pas les permissions requises.

app/views/cats/show.html.haml
.row
  .col-md-12
    .page-header
      %h1#type
        = @cat.name


.row
  .col-md-7
    %a{href: "/posts/new"}
      %button.btn.btn-primary{type: "button"}
        .glyphicon.glyphicon-edit
        Nouvelle annonce
  .col-md-1
    .glyphicon.glyphicon-search.h4.pull-right
  .col-md-4
    %form{action: "/page/search", method: "get"}
      %input.form-control{id: "q", name: "q", placeholder: "Rechercher une annonce", type: "text"}

%br

.panel.panel-default.panel-body.no-padding
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
        %th
        %th
          Titre
        %th
          Prix
        %th
          Auteur
        %th
          Annonce
    %body
      - @posts.each do |p|
        - if p.cat_id == @cat.id
          - @author = User.find(p.user_id)
          %tr
            %td
            %td
              - if p.image1?
                = image_tag p.image1.url(:square), width: "50px", height: "50px", class: "img-rounded"
              - else
                = image_tag "/images/img/default-square.png", width: "50px", height: "50px", class: "img-rounded"
            %td
              = p.title
            %td
              = p.price
              = "€"
            %td
              = @author.prenom
              = @author.nom
            %td
              %a{href: "/posts/#{p.id}"}
                .glyphicon.glyphicon-list-alt.h4
            %td

    

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for :comment, url: comment_path(@comment), method: :patch do |f| %>
  <% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Caddiie
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body

    .navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/page/index"}
            .glyphicon.glyphicon-chevron-left
            .glyphicon.glyphicon-shopping-cart
            .glyphicon.glyphicon-chevron-right
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li{id: "l1"}
              %a{href: "/page/index"}
                .glyphicon.glyphicon-home
                Accueil
            %li{id: "l2"}
              %a{href: "/cats/index"}
                .glyphicon.glyphicon-th
                Categories
            %li{id: "l3"}
              %a{href: "/profil/list"}
                .glyphicon.glyphicon-user
                Membres
            - if current_user.try(:admin?)
              %li{id: "l4"}
                %a{href: "/reports/index"}
                  .glyphicon.glyphicon-lock
                  Admin Panel


          %form.navbar-form.navbar-left{action: "/page/search", method: "get"}
            %input.form-control.col-lg-8{id: "q", name: "q", placeholder: "Rechercher une annonce", type: "text"}


          %p.navbar-text.pull-right
            - if user_signed_in?
              Logged in as
              = succeed "." do
                %strong= current_user.email
              = link_to 'Mon profil', "/profil/#{current_user.id}", :class => 'navbar-link'
              |
              \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
            - else
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
            - if notice
              %p.navbar-text.pull-right= notice
            - if alert
              %p.navbar-text.pull-right= alert

    .navbar.navbar-default.navbar-static-top


    .container
      = yield

:javascript
  jQuery(function(){
      var kKeys = [];
      function Kpress(e){
          kKeys.push(e.keyCode);
          if (kKeys.toString().indexOf("38,38,40,40,37,39,37,39,66,65") >= 0) {
              jQuery(this).unbind('keydown', Kpress);
              kExec();
          }
      }
      jQuery(document).keydown(Kpress);
  });
  function kExec(){
    alert("https://www.youtube.com/watch?v=pWsoz4GCAsY");
  }

app/views/page/index.html.haml
.jumbotron
  %h1
    .glyphicon.glyphicon-chevron-left
    .glyphicon.glyphicon-shopping-cart
    .glyphicon.glyphicon-chevron-right

  %h1 Caddiie




.row{style: "text-align:center;"}
  .col-md-12
    %a{href: "/cats/index"}
      %button.btn.btn-primary.btn-lg.btn-idx.pull-left{type: "button"}
        .glyphicon.glyphicon-eye-open
        %br
        Parcourir les annonces
    %a{href: "/posts/new"}
      %button.btn.btn-primary.btn-lg.btn-idx{type: "button"}
        .glyphicon.glyphicon-edit
        %br
        Déposer une annonce
    %button.btn.btn-primary.btn-lg.btn-idx.pull-right{type: "button"}
      .glyphicon.glyphicon-search
      %form{action: "/page/search", method: "get"}
        %input.form-control{id: "q", name: "q", placeholder: "Rechercher une annonce particulière", type: "text"}




%script $('#l1').attr('class','active')

app/views/page/new_admin.html.haml
- if current_user.try(:admin?)

  - @users.each do |u|
    - if @param_admin = u.id
      - u.update_attribute :admin, true

  %a{href: "/profil/#{@param_admin}"}
    Retour

- else
  Erreur

app/views/page/profil_search.html.haml
.row
  .col-md-12
    .page-header
      %h1
        recherche de "
        = @recherche
        "


.row
  .col-md-7
  .col-md-1
    .glyphicon.glyphicon-search.h4.pull-right
  .col-md-4
    %form{action: "/page/profil_search", method: "get"}
      %input.form-control{id: "q", name: "q", placeholder: "Rechercher un membre", type: "text"}
%br

- def dice_coefficient(a, b)
  - a_bigrams = a.each_char.each_cons(2).to_set
  - b_bigrams = b.each_char.each_cons(2).to_set
  - overlap = (a_bigrams & b_bigrams).size
  - total = a_bigrams.size + b_bigrams.size
  - dice  = overlap * 2.0 / total
  - dice

- h = Hash.new
- @users.each do |u|
  - h[u.id] = dice_coefficient(u.nom,@recherche) + dice_coefficient(u.prenom,@recherche)
  %p

- tri = h.sort_by { |key, value| value}


.list-group
  - tri.reverse.each do |key, value|
    - if value > 0.0
      - @users.each do |u|
        - if u.id == key
          %a.list-group-item{href: "/profil/#{u.id}"}

            - if u.avatar?
              = image_tag u.avatar.url(:square), width: "50px", height: "50px", class: "img-circle"
            - else
              = image_tag "/images/avt/default-square.png", width: "50px", height: "50px", class: "img-circle"

            .col-md-2.col-md-offset-2.mid
              = u.prenom
            .col-md-2.mid
              = u.nom
            .col-md-2.mid
              = u.promo
            .col-md-2.mid
              = u.email

app/views/page/search.html.haml
.row
  .col-md-12
    .page-header
      %h1
        recherche de "
        = @recherche
        "

- def dice_coefficient(a, b)
  - a_bigrams = a.each_char.each_cons(2).to_set
  - b_bigrams = b.each_char.each_cons(2).to_set
  - overlap = (a_bigrams & b_bigrams).size
  - total = a_bigrams.size + b_bigrams.size
  - dice  = overlap * 2.0 / total
  - dice

- h = Hash.new
- @posts.each do |p|
  - h[p.id] = dice_coefficient(p.text,@recherche) + 2 * dice_coefficient(p.title,@recherche)
  %p

- tri = h.sort_by { |key, value| value}

.list-group
  - tri.reverse.each do |key, value|
    - if value > 0.0
      - @posts.each do |p|
        - if p.id == key
          %a.list-group-item{href: "/posts/#{p.id}"}

            - if p.image1?
              = image_tag p.image1.url(:square), width: "50px", height: "50px", class: "img-rounded"
            - else
              = image_tag "/images/avt/default-square.png", width: "50px", height: "50px", class: "img-rounded"

            .col-md-2.mid
              = p.title
            .col-md-2.mid
              = p.price
              = "€"

app/views/page/validation.html.haml
- if current_user.try(:admin?)

  - @users.each do |u|
    - if @param_val = u.id
      - u.update_attribute :val, true

  %a{href: "/profil/#{@param_val}"}
    Retour

- else
  Erreur

app/views/posts/edit.html.haml
- if @post.user_id === current_user.id || current_user.try(:admin?)

  .row
    .col-md-12
      .page-header

  %h1 Modifier l'annonce:
  = form_for :post, url: post_path(@post), method: :patch do |f|
    - if @post.errors.any?
      #error_explanation
        %h2
          = pluralize(@post.errors.count, "error")
          prohibited
          this post from being saved:
        %ul
          - @post.errors.full_messages.each do |msg|
            %li= msg
    .row
      .col-md-12
        %h3.col-md-2
          = f.label :Titre
        .col-md-10
          .col-xs-4
          %br/
          = f.text_field :title
      .col-md-12
        %h3.col-md-2
          = f.label :Catégorie
        .col-md-10
          %br/
          = collection_select :post, :cat_id, @cats, :id, :name, { :include_blank => "Choisir la Catégorie ?"}
      .col-md-12
        %h3.col-md-2
          = f.label :Prix
        .col-md-10
          .col-xs-4
          %br/
          = f.number_field :price
      .col-md-12
        %h3.col-md-2
          = f.label :Description
        .col-md-10
          .col-xs-4
          %br/
          = f.text_area :text
      .col-md-12
        %h3.col-md-2
          = f.label :image1
        .col-md-10
          .col-xs-4
          %br/
          = f.file_field :image1
      .col-md-12
        %h3.col-md-2
          = f.label :image2
        .col-md-10
          .col-xs-4
          %br/
          = f.file_field :image2
      .col-md-12
        %h3.col-md-2
          = f.label :image3
        .col-md-10
          .col-xs-4
          %br/
          = f.file_field :image3
      .col-md-12
        %h3.col-md-2
          = f.label :image4
        .col-md-10
          .col-xs-4
          %br/
          = f.file_field :image4
      .col-md-12
        %h3.col-md-2
          = f.label :image5
        .col-md-10
          .col-xs-4
          %br/
          = f.file_field :image5
    %div
      %h3
        = f.submit
  = link_to 'Back', posts_path

- else
  Accès refusé

app/views/posts/new.html.haml
- if user_signed_in? && current_user.try(:val?)

  .row
  .col-md-12
    .col-md-2
    .col-md-6
      .panel.panel-default
        .panel-body
          %h1 Nouvelle annonce :
          = form_for :post, url: posts_path do |f|
            .row
              .col-md-12
                .col-lg-10
                  %br/
                  = f.text_field :title, placeholder: " Titre"
              .col-md-12
                .col-md-10
                  %br/
                  = collection_select :post, :cat_id, @cats, :id, :name, { :include_blank => "Choisir la Catégorie ?"}
              .col-md-12
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.number_field :price, placeholder: " number"
              .col-md-12
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.text_area :text, placeholder: " text"
              .col-md-12
                %p.col-md-2
                  = f.label :image1
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.file_field :image1
              .col-md-12
                %p.col-md-2
                  = f.label :image2
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.file_field :image2
              .col-md-12
                %p.col-md-2
                  = f.label :image3
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.file_field :image3
              .col-md-12
                %p.col-md-2
                  = f.label :image4
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.file_field :image4
              .col-md-12
                %p.col-md-2
                  = f.label :image5
                .col-md-10
                  .col-xs-4
                  %br/
                  = f.file_field :image5
                %div

            %div
              %p
                = f.submit

- else
  Accès interdit

app/views/posts/show.html.haml
.row
  .col-md-12
    .page-header

.row
  .col-md-12
    .col-md-4
      - if @post.image1?
        = image_tag @post.image1.url(:medium), width: "300px",class: "img-thumbnail img-rounded"
      - else
        = image_tag "/images/img/default-medium.png", width: "300px",class: "img-thumbnail img-rounded"

      %br

      - if user_signed_in? && current_user.try(:val?)

        %br
        %a{href: "/reports/new"}
          %button.btn.btn-primary.btn-lg{type: "button"} Signaler cette annonce
        %br
        %br
        .panel.panel-info
          .panel-heading
            %h3.panel-title Author Box
          .panel-body
            .row
              .col-md-12
                .col-md-4
                  %a{href: "/posts/#{@post.id}/edit/"}
                    %h4.glyphicon.glyphicon-edit
                    Modifier
                .col-md-4
                  %a{href: ""}
                    %h4.glyphicon.glyphicon-warning-sign
                    Signaler
                .col-md-4
                  %a{href: ""}
                    %h4.glyphicon.glyphicon-folder-open
                    Archiver
    .col-md-8
      .panel.panel-default
        .panel-heading
          %h3
            %strong
            = @post.title
            .badge.pull-right
              = @post.price
              ="€"
          %h5
            Postée par
            %strong
            = @author.nom

        - if user_signed_in? && current_user.try(:val?)
          .panel-body
            %h4
              %strong
              = @post.text

      - if user_signed_in? && current_user.try(:val?)
        .panel.panel-default
          .panel-body
            .col-md-12
              .col-md-3
                - if @post.image2?
                  = image_tag @post.image2.url(:medium) , height: "120px",class: "img-rounded"
              .col-md-3
                - if @post.image3?
                  = image_tag @post.image3.url(:medium) , height: "120px",class: "img-rounded"
              .col-md-3
                - if @post.image4?
                  = image_tag @post.image4.url(:medium) , height: "120px",class: "img-rounded"
              .col-md-3
                - if @post.image5?
                  = image_tag @post.image5.url(:medium) , height: "120px",class: "img-rounded"

      .panel.panel-default
        .panel-body
          %h2 Commentaires
          - @post.comments.each do |comment|


            %blockquote
              %p= comment.text
              %small
                - @user = User.find(comment.user_id)
                = @user.nom



          .col-md-1
          .col-md-8
            %h3 Ajouter un commentaire
            = form_for([@post, @post.comments.build]) do |f|

              %p
                = f.text_area :text

              %p
                = f.submit

app/views/profil/list.html.haml
- if user_signed_in? && current_user.try(:val?)

  .row
    .col-md-12
      .page-header
        %h1
          Membres
  .row
    .col-md-7
    .col-md-1
      .glyphicon.glyphicon-search.h4.pull-right
    .col-md-4
      %form{action: "/page/profil_search", method: "get"}
        %input.form-control{id: "q", name: "q", placeholder: "Rechercher un membre", type: "text"}

  %br

  .panel.panel-default.panel-body.no-padding
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th
          %th
          %th
            Prénom
          %th
            Nom
          %th
            Promo
          %th
            Mail
          %th
            Profil


      %tbody
        - @users.each do |u|
          %tr
            %td
            %td
              - if u.avatar?
                = image_tag u.avatar.url(:square), width: "50px", height: "50px", class: "img-circle"
              - else
                = image_tag "/images/avt/default-square.png", width: "50px", height: "50px", class: "img-circle"

            %td
              = u.prenom
            %td
              = u.nom
            %td
              = u.promo
            %td
              = u.email
            %td
              %a{href: "/profil/#{u.id}"}
                .glyphicon.glyphicon-user.h4




  %script $('#l3').attr('class','active')

- else
  Accès refusé

app/views/reports/index.html.haml
- if current_user.try(:admin?)

  .row
    .col-md-12
      .page-header
        %h1 Admin panel

  .row
    .col-md-12
      .col-md-12
        %a{href: "/cats/new"}
          %button.btn.btn-primary{type: "button"} Nouvelle catégorie

  %br

  .row
    .col-md-12
      .col-md-6
        .well
          %h3 Signalements
          - @reports.each do |r|
            %p
              = r.text
              = link_to 'Supprimer', report_path(r), method: :delete, data: { confirm: 'Are you sure?' }

          %script $('#l4').attr('class','active')
      .col-md-6
        .well
          %h3 Utilisateurs non-validés
          - @users.each do |u|
            - if u.val === false
              %p
                = link_to u.email, "/profil/#{u.id}"

- else
  Accès refusé

app/views/reports/new.html.haml
%h1 Nouveau signalement

= form_for :report, url: reports_path do |f|
  %p
    = f.label :text
    %br/
    = f.text_area :text
  %p
    = f.submit

app/views/reports/show.html.haml
%p
  %strong Text:
  = @report.text